### ISSUE TITLE
Admin Teacher - form appearance and behavior bugs

### ISSUE THREAD

**Issue by AJIex1s** [Mallusca/JournaCore#45]
https://www.screencast.com/t/1KjVeMJudv

**Comment by AJIex1s** [comment]
Аналогичное поведение у студента. Наверное стоит для едит формы добавить лейблы, а для криейт формы оставить без лейблов, через иф в вёрстке. Погугли какие сейчас модные формы ещё.

**Comment by Mallusca** [comment]
fixed
