### ISSUE TITLE
Admin Student Group Subscriptions - incorrect names

### ISSUE THREAD

**Issue by AJIex1s** [Mallusca/JournaCore#48]
Тарифные планы
![image](https://user-images.githubusercontent.com/6532054/89097288-4ca45b80-d3e6-11ea-8f44-ec2e4a46df78.png)
Текущие подписки\Подписки
![image](https://user-images.githubusercontent.com/6532054/89097370-06033100-d3e7-11ea-8d98-d339aa073354.png)

**Comment by Mallusca** [comment]
fixed
